"""add tag, review, and shipmenttaglink

Revision ID: df48ca9c5807
Revises: a39bd4bd194b
Create Date: 2026-06-07 16:53:14.540270

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql
from app.database.models import Tag

# revision identifiers, used by Alembic.
revision: str = 'df48ca9c5807'
down_revision: Union[str, Sequence[str], None] = 'a39bd4bd194b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tag',
                    sa.Column('id', sa.UUID(), nullable=False),
                    sa.Column(
                        'name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
                    sa.Column('instructions',
                              sqlmodel.sql.sqltypes.AutoString(), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('shipment_tag_link',
                    sa.Column('shipment_id', sa.Uuid(), nullable=False),
                    sa.Column('tag_id', sa.Uuid(), nullable=False),
                    sa.ForeignKeyConstraint(
                        ['shipment_id'], ['shipment.id'], ),
                    sa.ForeignKeyConstraint(['tag_id'], ['tag.id'], ),
                    sa.PrimaryKeyConstraint('shipment_id', 'tag_id')
                    )
    # add tag entries in the database
    tags = [
        {"name": "Fragile", "instructions": "Handle with care, fragile items."},
        {"name": "Perishable", "instructions": "Store in a cool place, perishable goods."},
        {"name": "Heavy", "instructions": "Use proper lifting techniques, heavy item."},
        {"name": "Urgent", "instructions": "Deliver as soon as possible, urgent shipment."},
    ]

    for tag in tags:
        op.execute(
            f"""
            INSERT INTO tag (id, name, instructions)
            VALUES (gen_random_uuid(), '{tag['name']}', '{tag['instructions']}')
            """
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('shipment_tag_link')
    op.drop_table('tag')
    # ### end Alembic commands ###
